{% set name = "cadabra2" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kpeeters/cadabra2/archive/{{ version }}.tar.gz
  sha256: 1ba2dd2c91e6678a49a136c181da4ec424f1cec9a7172cf95fd1b0c04c253217
  patches:
    - cdd2fb45dc3e280d6f3834b54d9f7d612b604155.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
    - {{ cdt('libice-devel') }}  # [linux]
    - {{ cdt('libsm-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}  # [linux]
    - {{ cdt('libxcomposite-devel') }}  # [linux]
    - {{ cdt('libxcursor-devel') }}  # [linux]
    - {{ cdt('libxdamage-devel') }}  # [linux]
    - {{ cdt('libxext-devel') }}  # [linux]
    - {{ cdt('libxi-devel') }}  # [linux]
    - {{ cdt('libxinerama-devel') }}  # [linux]
    - {{ cdt('libxfixes-devel') }}  # [linux]
    - {{ cdt('libxrandr-devel') }}  # [linux]
    - {{ cdt('libxrender-devel') }}  # [linux]
    - {{ cdt('libxtst-devel') }}  # [linux]
    - {{ cdt('mesa-libEGL-devel') }}  # [linux]
    - {{ cdt('mesa-libGL-devel') }}  # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]

  host:
    - python
    - gmp
    - boost-cpp
    - libuuid
    - sqlite
    - pcre
    - gtkmm-3.0
    - glibmm
    - cairomm-1.0
    - glib
    - sigcpp-2.0
    - pangomm-1.4
    - cairo
    - atkmm-1.6
    - nlohmann_json
    #- xtl
    - jsoncpp
    #- xeus
    #- zeromq
    #- cppzmq
    - gtkmm
    - pybind11
    # Needed for ctest
    - sympy
  run:
    - boost-cpp
    - python
    - sympy
    - matplotlib-base
    # Remove these when they get run_exports
    - {{ pin_compatible("cairo") }}
    - {{ pin_compatible("glibmm") }}
    - {{ pin_compatible("glib") }}

test:
  imports:
    - cadabra2

about:
  home: https://github.com/kpeeters/cadabra2
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: a field-theory motivated approach to computer algebra

extra:
  recipe-maintainers:
    - isuruf
